### ISSUE TITLE
Static lists

### ISSUE THREAD

**Issue by jprider63** [rushmorem/publicsuffix#14]
I'd like to create `List`s statically at compile-time (I don't want to rely on the internet or ship the dat file). I've implemented this [here](https://github.com/jprider63/staticpublicsuffix/blob/master/src/lib.rs#L7) using `lazy_static!` and `include_str!`. Currently, this should extract the `&str` at compile-time and lazily build the list at run-time. Would you be interested in including this static list in this crate? 

I just created the pull request #13, which adds a function `from_str` to create a `List`. This should eliminate the need to call `to_string` which might save some memory.

**Comment by rushmorem** [comment]
Thank you. I've just released `v1.5.0`, which includes your pull request.

> Would you be interested in including this static list in this crate?

Since the Public Suffix List is a living document, I prefer that caching strategies, like the `psl` crate, be maintained externally.

**Comment by jprider63** [comment]
Ok no worries. I'll release `staticpublicsuffix` as a separate library in case anyone else needs this functionality.

**Comment by rushmorem** [comment]
Cool, thanks.

**Comment by rushmorem** [comment]
@jprider63 You may be interested [in the newer replacement](https://crates.io/crates/psl) of this crate [which is a lot faster](https://github.com/rushmorem/publicsuffix/issues/15). See [some benchmarks](https://github.com/addr-rs/pslbench) against a `C` library, `libpsl` and a `PyPy` one, `publicsuffix`.
