### ISSUE TITLE
1.5.2 release

### ISSUE THREAD

**Issue by pfernie** [rushmorem/publicsuffix#16]
Similar to this [issue](https://github.com/seanmonstar/reqwest/issues/345), `native-tls 0.2` is now required to build on hosts with newer versions of openssl. This dependency bump already exists on `master`, could you release `1.5.2`?

**Comment by rushmorem** [comment]
Done. Thanks!

You may also be interested in https://crates.io/crates/psl which is a complete rewrite of this library with [serious performance optimization](https://github.com/addr-rs/pslbench). See https://github.com/rushmorem/publicsuffix/issues/15 for details.
