### ISSUE TITLE
Provide alternate tls implementation options

### ISSUE THREAD

**Issue by pfernie** [rushmorem/publicsuffix#17]
Per an [issue raised on user_agent](https://github.com/pfernie/user_agent/issues/24), the default features of `publicsuffix` end up pulling in a `native-tls`/`openssl` dependency that some users would like to avoid. `cookie_store` (the intermediate dependency relying on `publicsuffix`) was updated to disable default features, which removes the issue, but raising the issue here as well for your consideration to either:
1. support alternate tls implementations (`rustls-tls`), although issue #1 suggests perhaps this is more burden than you'd like in this crate.
2. move the `remote_list` functionality out of the `publicsuffix` crate and into a separate crate
3. simply not including it as a default feature.

**Comment by rushmorem** [comment]
v2 dropped the `remote_list` feature entirely :slightly_smiling_face:

**Comment by rushmorem** [comment]
v2 dropped the `remote_list` feature entirely :slightly_smiling_face:
