### ISSUE TITLE
`has_known_suffix` always return true

### ISSUE THREAD

**Issue by Diggsey** [rushmorem/publicsuffix#30]
This is a security vulnerability, as programs may rely on this to screen out local domains, eg. "example.svc.local".

I understand that the algorithm described on https://publicsuffix.org/list/ specifies that:
> If no rules match, the prevailing rule is "*".

However, this is for a specific use-case: when determining what part of the domain is the public suffix. Using this rule when determining whether the suffix is "known" is a huge security hole, as it essentially treats all domains as "known".

Specifically the "type" should be `None`, if the wildcard rule is used as a fallback.

**Comment by bradfier** [comment]
#31 contains a possible minimal fix for this behaviour.

Changing the type to be `None` for wildcard matched domains is probably the more correct solution, but would mean bigger changes to how the public test suite is run and interpreted.

**Comment by rushmorem** [comment]
Fixed by https://github.com/rushmorem/publicsuffix/pull/31
