### ISSUE TITLE
Domains with underscores are considered as invalid

### ISSUE THREAD

**Issue by rozhn0v** [rushmorem/publicsuffix#33]
Hello! The library fails to parse domains with underscores.
```rust
let list = List::fetch().unwrap();
let domain = list.parse_domain("_jabber._tcp.gmail.com")
    .expect("underscores in labels are valid");
```

**Comment by eggyal** [comment]
This appears to be what [`List::parse_dns_name`](https://docs.rs/publicsuffix/1.5.4/publicsuffix/struct.List.html#method.parse_dns_name) was [introduced for](https://github.com/rushmorem/publicsuffix/pull/7), however if the root contains an underscore (or any other byte that's valid in a DNS label but not in a hostname) then the following check causes [`DnsName::domain`](https://docs.rs/publicsuffix/1.5.4/publicsuffix/struct.DnsName.html#method.domain) to return `None` which surely is not correct?

https://github.com/rushmorem/publicsuffix/blob/149e9fd1b9cf02503b2a6561cb9e80f9a4c2da71/src/lib.rs#L537

Can we remove this check, please?

**Comment by eggyal** [comment]
Actually, per https://github.com/rushmorem/publicsuffix/pull/7#issuecomment-318928690:

> Some people, myself included, are using this library to validate "registrable" domain names. As such, `domain.root()` must only return registrable domain names.

Nothing in the standards prevent registries from offering for registration domains containing bytes that are disallowed in hostnames, though I accept as a matter of policy most if not all do impose such a restriction.  So whether this check strictly belongs in this library is not so clear.

However, if it is to remain, could we instead add `root` and `suffix` members to `DnsName` that bypass these checks?

**Comment by rushmorem** [comment]
> Can we remove this check, please?

@eggyal [psl](https://crates.io/crates/psl) sounds like a better fit for your use case. It's lower level and only checks to see if the input ends with a public suffix. It doesn't try to validate the syntax of the hostname. As a bonus it's much faster, doesn't have any dependencies and it is `no_std`.

**Comment by rushmorem** [comment]
@eggyal Does [this API](https://docs.rs/addr/0.6.1/addr/dns/struct.Name.html) work well for your use case? It should eliminate any false negatives you were having but your feedback here is highly appreciated.

**Comment by eggyal** [comment]
I've taken a quick look and indeed it does appear to fit the bill.  Thanks @rushmorem !

**Comment by rushmorem** [comment]
Awesome! Thanks for the feedback.

**Comment by rushmorem** [comment]
I believe this is now fixed, both in this crate and in `addr` where `parse_dns_name` was moved to.
