### ISSUE TITLE
New release for new dependencies

### ISSUE THREAD

**Issue by dmitrmax** [rushmorem/publicsuffix#41]
Hi!

Would you please make new tag? Primarily because 2.2.3 pulls idna 0.3.0 as dependency and master is pinned to 0.5.0.

Thanks in advance!

**Comment by jqnatividad** [comment]
+1 on a new release please @rushmorem

**Comment by torokati44** [comment]
yes please :no_mouth:

**Comment by rushmorem** [comment]
Thanks guys! `v2.3.0` is now out.

**Comment by torokati44** [comment]
Awesome, thank you!
